version: '3.3'
services:
  agent:
    image: harbor.elofun.net/devops/portainer-agent:0.0.1
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ee:2.19.1
    #image: elfdev/portainer-demo:0.0.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == d1]
      labels:
        - ingress.host=infra.hongduydevops.id.vn
        - ingress.port=9000
networks:
  agent_network:
    attachable: true
  traefik_public:
    external: true

volumes:
  portainer_data:
